[editor]
name = "Shuoan Li"
degree = "Undergraduate, 2022"

[article.1]
title = "Investigating the interaction of pleasantness and arousal and the role of aesthetic emotions on episodic memory using a musical what-where-when paradigm"
doi = "https://doi.org/10.1080/02699931.2023.2185206"
authors = "Safiyyah Nawaz & Diana Omigie"
journal = "Emotion"
publish = "Volume 37, issue 1, 23 Mar 2023"
category = "Cognition and Emotion"
summary = "为了验证愉快的音乐如何积极地影响情境记忆的编码，本研究使用了一个在线的 “何时何地 ”范式来评估音乐对丰富时空环境中的情境记忆的影响，发现与高唤醒性的节选相比，低唤醒性的节选与更好的回忆表现有关。"
abstract = "Recent evidence suggests that the presence of music experienced as pleasant positively influences episodic memory (EM) encoding. However, it is unclear whether this impact of pleasant music holds regardless of how arousing the music is, and what influence, if any, music-induced aesthetic emotions have. Furthermore, most music EM studies have used verbal or facial memory tasks limiting the generalisability of these findings to everyday EMs with spatiotemporal richness. The current study used an online what-where-when paradigm to assess music's influence on EM encoding in a rich spatiotemporal environment. 105 participants carried out the what-where-when task in the presence of either silence or one of four musical stimuli falling into the four corners of the 2-D circumplex emotion model. We observed an interaction effect between the pleasantness and arousingness of music stimuli, whereby for pleasant stimuli, the low arousing excerpt was associated with better recall performance compared to the high arousing excerpt. We also observed that, across all excerpts, experience of negative aesthetic emotions was associated with compromised recall performance. Together, our results confirm the deleterious influence arousing stimuli can have on memory and support the notion that aesthetic-emotional experience of music can influence how memories are encoded in everyday life."
keywords = "music, emotion, aesthetic, episodic memory, what-where-when"

[article.2]
title = "2This is a title"
doi = "https://doi.org/example2"
authors = "2A B & C D"
journal = "2Journal B"
publish = "2023, 23(4), 666-667"
category = "Face"
summary = "2This is a summary"
abstract = "2This is the abstract"
keywords = "2This is keywords"
